name: jcp
description: "Cars parts"

publish_to: 'none'

version: 1.4.1+8

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.1.0
  provider: ^6.1.2
  intl: ^0.18.1
  flutter_svg: ^2.0.10+1
  intl_phone_field: ^3.2.0
  get: ^4.6.6
  sms_autofill: ^2.3.1
  flutter_spinkit: ^5.2.1
  image_picker: ^1.0.7
  http: ^1.2.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  flutter_local_notifications: ^17.2.1+2
  msh_checkbox: ^2.0.1
  auto_direction: ^0.0.6
  permission_handler: ^11.3.1
  multi_select_flutter: ^4.1.3
  change_app_package_name: ^1.4.0
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.2.7
  flutter_launcher_icons: ^0.14.1
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter_keyboard_visibility: ^6.0.0
  cloud_firestore: ^5.6.2
  auto_size_text: ^3.0.0
  keyboard_avoider: ^0.2.0
  flutter_ringtone_player: ^4.0.0+4
  overlay_support: ^2.1.0
  image: ^4.5.4
  cached_network_image: ^3.4.1
  crypto: ^3.0.6
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.14.2
  app_links: ^6.1.4
  keyboard_actions: ^4.1.0
  connectivity_plus: ^7.0.0
  wechat_assets_picker: ^9.4.1




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"


  min_sdk_android: 21

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/
    - assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/font/Tajawal-Medium.ttf